### ISSUE TITLE
Refactor The Code and write the README

### ISSUE THREAD

**Issue by Elijah1111** [evelyn-needham/Voicelle#2]
The Code should be made to be more readable. Comments are important, also the names of the files should be named in a fashion that pertains to their use. Is there a main script for this? How do the various parts work together?

Make a readme file describing the required libraries and how to use it.

**Comment by evelyn-needham** [comment]
Sounds good. I’ll have this done by our next meeting on Saturday

**Comment by Elijah1111** [comment]
Make sure to finish up the README
